name: Build APK Game

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Ambil Source Code
      uses: actions/checkout@v4

    - name: 2. Setup Java 17 (Wajib untuk Gradle)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 3. Install Pendukung Utama & Paksa Android SDK Manager
      run: |
        sudo apt-get update
        sudo apt-get install -y libtool-bin ccache autoconf automake pkg-config libltdl-dev
        sudo apt-get install -y git zip unzip python3-pip cmake libffi-dev libssl-dev
        sudo apt-get install -y aidl
        pip install --upgrade buildozer cython virtualenv
        
        # Mendownload alat resmi dari Google untuk menyetujui lisensi di awal
        mkdir -p $HOME/cmdline-tools
        curl -o cmdline.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q cmdline.zip -d $HOME/cmdline-tools
        
        # Trik Utama: Menandatangani semua lisensi Google Android (Termasuk versi 37) secara otomatis
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/
        yes | $HOME/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses

    - name: 4. Build APK Secara Bersih
      run: |
        # Sekarang Buildozer bebas jalan karena semua pintu lisensi sudah kita buka di awal
        buildozer android debug

    - name: 5. Upload APK ke Hasil Akhir
      uses: actions/upload-artifact@v4
      with:
        name: Game-APK-Siap-Instal
        path: bin/*.apk
